import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { properties, imageUrl } from "@/lib/properties";
import { money } from "@/lib/site";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}) {
 const p=await properties.getBySlug((await params).slug);
 return p ? {title:p.title+" | "+p.location,description:p.listing?.summary || p.description.slice(0,160),alternates:{canonical:"/properties/"+p.slug},openGraph:{images:[p.image]}} : {title:"Property not found"};
}
export default async function Detail({params}:{params:Promise<{slug:string}>}) {
 const p=await properties.getBySlug((await params).slug);if(!p || !p.listing)notFound();const d=p.listing;
 const whatsapp="https://wa.me/447773754121?text="+encodeURIComponent("Hi ABS Properties, I am interested in "+d.address_line1+" / "+d.reference+". Please can I have more information?");
 const facts = [["Reference",d.reference],["Status",d.status],["Property type",d.property_type],["Category",d.category],["Bedrooms",String(d.bedrooms)],["Bathrooms",String(d.bathrooms)],["Reception rooms",String(d.reception_rooms)],["Furnishing",d.furnishing],["Available from",d.available_date],["Deposit",d.deposit == null ? "" : money(d.deposit)],["Holding deposit",d.holding_deposit == null ? "" : money(d.holding_deposit)],["Minimum tenancy",d.minimum_tenancy],["Council tax",d.council_tax],["EPC",d.epc]].filter(([,v])=>v);
 return <div className="container detail"><Link href="/properties" className="text-link">Back to properties</Link><div className="detail-heading"><div><p className="overline">{p.location} ? {p.postcode}</p><h1>{p.title}</h1></div><p className="detail-price">{d.price_qualifier} {money(d.price)} <span>{d.price_unit === "sale" ? "" : d.price_unit}</span></p></div><div className="detail-photo"><Image src={p.image} alt={p.title} fill unoptimized preload sizes="100vw"/><span className="photo-label">{d.status}</span></div><div className="editor-images">{d.images.slice(1).map((path,i)=><a key={path} href={imageUrl(path)} target="_blank" rel="noreferrer"><Image src={imageUrl(path)} unoptimized width={400} height={270} alt={p.title+" ? image "+(i+2)}/></a>)}</div><div className="detail-layout"><div><h2>About this property</h2><p style={{whiteSpace:"pre-line"}}>{d.description}</p>{d.features.length>0 && <><h3>Key features</h3><ul className="feature-list">{d.features.map(f=><li key={f}>{f}</li>)}</ul></>}<h3>Property information</h3><dl className="facts">{facts.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{d.floorplan && <p><a href={d.floorplan} target="_blank" rel="noreferrer">View floorplan</a></p>}{d.brochure && <p><a href={d.brochure} target="_blank" rel="noreferrer">Download brochure</a></p>}{d.latitude != null && d.longitude != null && <a href={"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(d.latitude+","+d.longitude)} target="_blank" rel="noreferrer">View location on map</a>}</div><aside className="enquiry-panel"><h2>Interested in this property?</h2><Link className="button" href={"/contact?property="+p.slug}>Book a viewing</Link><p>Send a request and our team will confirm availability.</p><a className="button secondary" href={whatsapp} target="_blank" rel="noreferrer">WhatsApp enquiry</a><Link className="text-link" href="/contact">Contact agent</Link></aside></div></div>;
}
